### ISSUE TITLE
Deadlock warning from the "Expand all nested JSON" context action preview

### ISSUE THREAD

**Issue by danberindei** [ICoder0/groom#9]
Happens to me the first time I try to use the "Expand all nested JSON" context action after a restart, later attempts just say "Preview isn't available".

IntelliJ IDEA 2022.1

```
java.lang.Throwable: Must not start write action from within read action in the other thread - deadlock is coming
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:118)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:362)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:350)
	at com.icoder0.groom.inspection.NestedJsonInspection$NestedJsonQuickFixFully.applyFix(NestedJsonInspection.kt:135)
	at com.icoder0.groom.inspection.NestedJsonInspection$NestedJsonQuickFixFully.applyFix(NestedJsonInspection.kt:108)
	at com.intellij.codeInspection.LocalQuickFix.generatePreview(LocalQuickFix.java:99)
	at com.intellij.codeInspection.ex.QuickFixWrapper.generatePreview(QuickFixWrapper.java:123)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.generatePreview(IntentionActionWithTextCaching.java:241)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.generatePreview(IntentionPreviewComputable.kt:97)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent(IntentionPreviewComputable.kt:59)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:37)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:32)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by BOFA1ex** [comment]
sorry for replying so late, did that recur anytime? give the example it better.
i try this inspection working on IntelliJ IDEA 2021.3.

`WriteCommandAction$BuilderImpl.run`
it invoke an predicate `!dispatchThread && application.isReadAccessAllowed`, it was necessary to make sure these arguments.



> this feature was refer to below doc
> https://plugins.jetbrains.com/docs/intellij/quick-fix.html#update-the-annotator

**Comment by danberindei** [comment]
@BOFA1ex no worries, it's nothing critical.

> i try this inspection working on IntelliJ IDEA 2022.3.

Did you mean 2021.3?

It still happens for me every time I'm editing a JSON scratch file with a string value that contains escaped JSON and can be "unwrapped". E.g.

```json
{
  "a": "{\"a\":\"a\"}"
}
```

I'm not familiar with the IntelliJ plugin API, but I did see in the [LocalQuickFix javadoc](https://github.com/JetBrains/intellij-community/blob/master/platform/analysis-api/src/com/intellij/codeInspection/LocalQuickFix.java#L72-L74) that

```quote
   * Generate preview for this fix. This method is called outside write action,
   * even if {@link #startInWriteAction()} returns true. It's not allowed to modify
   * any physical PSI or spawn any actions in other threads within this method. 
```

**Comment by BOFA1ex** [comment]
@danberindei thanks for remind it
> i try this inspection working on IntelliJ IDEA 2021.3.

After that, I try to upgrade IDEA for 2022.1(Build #IU-221.5080.210), and then create JSON scratch file with example recurred. but it was working on `unwrapped escaped JSON` non-error.

![image](https://user-images.githubusercontent.com/30573693/167766863-f4019a84-cbd5-4406-8d36-6773bdaf5c49.png)
![image](https://user-images.githubusercontent.com/30573693/167767002-514296fe-a4cc-4f49-bdd8-055c8e1a2eca.png)

> I'm not familiar with the IntelliJ plugin API, but I did see in the [LocalQuickFix javadoc](https://github.com/JetBrains/intellij-community/blob/master/platform/analysis-api/src/com/intellij/codeInspection/LocalQuickFix.java#L72-L74) that

It's not available since `221.*`, so i could not found `#generatePreview` when did not upgrade intellij SDK version to `2022.1`.
```gradle
intellij {
    version = '2020.2' => '2022.1'
    sandboxDirectory = "${project.rootDir}/.sandbox"
    updateSinceUntilBuild = false
}
```
